version: '3.1'

services:

  db:
    image: mysql
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    restart: always
    ports:
      - 8080:8080